### ISSUE TITLE
好神金的addon（

### ISSUE THREAD

**Issue by LeafletXD** [TATyKeFei/gyakuten_saiban-Itemsadder-addon#1]
可以加个物品：成步堂异议时伸出的手臂右键或左键弹出异议（play_totem_animation）加声音

![成步堂的手臂](https://github.com/user-attachments/assets/bda9a352-3f54-48cd-969f-5e2a6d81be38)

![异议](https://github.com/user-attachments/assets/47136c75-0f00-4cb4-a76d-7a9de12ac45d)

**Comment by TATyKeFei** [comment]
可以，周末有空弄

**Comment by TATyKeFei** [comment]
![image](https://github.com/user-attachments/assets/e3f99e51-66eb-4682-9b65-ff9531c619ee)
弄完了，这个东西是从我服务器资源包分开出来的，才发现我很多路径忘记改了💦💦💦
